print (' ')
print (' ')
print (' Happy Ied Mubarak Everyone')
print (' Barakallah Fiik')
print (' Taqabbalallahu Minna Waminkum ')
print (' Minal Aidin Walfaidzin ')
print (' Mari Saling Maaf Memaafkan ')
print (' Semoga Masih Diberikan Kesempatan Untuk Bertemu Ramdhan Berikutnya ')
print (' ')
print (' ')
print ('-------------------------------------')
print ('      Achmad Kurniansyah Thalib      ')
print ('-------------------------------------')